### PR TITLE
Embed validator policies

### PR DESCRIPTION
**Pull request by rjerrems**
Adds:
- https://github.com/forseti-security/policy-library/blob/master/docs/bundles/scorecard-v1.md
- https://github.com/forseti-security/policy-library/blob/master/samples/serviceusage_allow_basic_apis.yaml

Addresses the adding policies part of this https://github.com/terraform-google-modules/terraform-example-foundation/issues/153

### CODE REVIEW

**Comment by bharathkkb** [comment]
looks like the yaml headers are missing ` # Copyright YEAR Google LLC` , we can probably use https://github.com/google/addlicense

**Comment by rjerrems** [comment]
@morgante one thing I noticed, is I had to modify the syntax of the policies to get this to work locally. When policies had:

```
spec:
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - organizations/**
```

I was getting:

```error: validating: FCV: auditing: core.dependencies.audit:25: eval_builtin_error: re_match: error parsing regexp: invalid nested repetition operator: `**````

With version 
```
terraform-validator version
Build version: 2020-03-05
```

Am I doing something wrong? when I removed the second `*` it seemed to run

**Comment by morgante** [comment]
@rjerrems This looks like https://github.com/forseti-security/config-validator/issues/142

I think we might need to do a new release of Terraform Validator to fix it.

**Comment by rjerrems** [comment]
Yeah there is also this open issue https://github.com/GoogleCloudPlatform/terraform-validator/issues/146

I tried downgrading validator to a older version and still had the same issue

**Comment by rjerrems** [comment]
FYI, this release of validator seems to be able to parse that syntax `2019-11-07` - although I didn't seem to be able to get this policy to report an error https://github.com/forseti-security/policy-library/blob/master/samples/serviceusage_allow_basic_apis.yaml

It did not report any issues, even if I added APIs not in the list in the plan

**Comment by rjerrems** [comment]
So I might need some of your help @morgante - I have tried to no avail to get a constraint violation with the updates syntax like this:

**Validator version:**

```
terraform-validator version
Build version: 2020-03-05
```

**Test contraint**

```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPRestrictedFirewallRulesConstraintV1
metadata:
  name: restrict-firewall-rule-world-open
  annotations:
    bundles.validator.forsetisecurity.org/forseti-security: v2.26.0
    bundles.validator.forsetisecurity.org/scorecard-v1: security
    description: Checks for open firewall rules allowing ingress from the internet.
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - organizations/*
  parameters:
    rules:
    - direction: INGRESS
      source_ranges:
      - 0.0.0.0/0
      enabled: 'true'
      rule_type: denied
```

**Terraform code**

```hcl
resource "google_compute_firewall" "default" {
  project = "prj-d-shared-base-xxxx"
  name    = "test-firewall"
  network = "projects/prj-d-shared-base-xxxx/global/networks/vpc-d-shared-private"

  source_ranges = ["0.0.0.0/0"]

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}
```

***terraform-validator convert output***

```json
    {
        "name": "//compute.googleapis.com/projects/prj-d-shared-base-xxxx/global/firewalls/test-firewall",
        "asset_type": "compute.googleapis.com/Firewall",
        "ancestry_path": "organization/000000000000/folder/000000000000/project/prj-d-shared-base-xxxx",
        "resource": {
            "version": "v1",
            "discovery_document_uri": "https://www.googleapis.com/discovery/v1/apis/compute/v1/rest",
            "discovery_name": "Firewall",
            "parent": "//cloudresourcemanager.googleapis.com/projects/prj-d-shared-base-xxxx",
            "data": {
                "allowed": [
                    {
                        "IPProtocol": "tcp",
                        "ports": [
                            "22"
                        ]
                    }
                ],
                "disabled": false,
                "logConfig": {
                    "enable": false
                },
                "name": "test-firewall",
                "network": "projects/prj-d-shared-base-xxxx/global/networks/vpc-d-shared-private",
                "priority": 1000,
                "sourceRanges": [
                    "0.0.0.0/0"
                ]
            }
        }
    }
```

**Terraform Validator output**

https://gist.github.com/rjerrems/2c9cd2c27c66679fd46c11fb74408007

**Pull request closed without merging**
