### PR TITLE
Fixes for build stability issues

### PR DESCRIPTION
**Pull request by daniel-cit**
This PR has fixes for:

- DNS default policy creation timeout issue in step `3-networks`
- ~Concurrent change of peering network in step `4-projects`~
- Access context manager policy deleted by external agent

**DNS error:**

```
       Error: Error creating ManagedZone: googleapi: Error 409: The resource 'entity.managedZone' named 'dz-n-shared-restricted-apis' already exists, alreadyExists
       
         on .terraform/modules/non-production.restricted_shared_vpc.restricted_googleapis/main.tf line 76, in resource "google_dns_managed_zone" "private":
         76: resource "google_dns_managed_zone" "private" {
       
       
       
       Error: Error creating Policy: googleapi: Error 409: The resource 'entity.policy' named 'default-policy' already exists, alreadyExists
       
         on ../../../3-networks/modules/restricted_shared_vpc/dns.tf line 44, in resource "google_dns_policy" "default_policy":
         44: resource "google_dns_policy" "default_policy" {

```

**Concurrent change error:**

```
     ×  Command: `gcloud access-context-manager perimeters describe sp_d_shared_restricted_default_perimeter_66c9 --policy 37660424834 --format=json` Access Context Manager perimeter sp_d_shared_restricted_default_perimeter_66c9 should include tst-bu1-d-sample-restrict-f770 project
     expected ["projects/1063179882416", "projects/799496908062"] to include "projects/958861554518"
     
     ×  Command: `gcloud access-context-manager perimeters describe sp_p_shared_restricted_default_perimeter_af27 --policy 37660424834 --format=json` Access Context Manager perimeter sp_p_shared_restricted_default_perimeter_af27 should include tst-bu1-p-sample-restrict-9b4a project
     expected ["projects/477683701596", "projects/589538538791"] to include "projects/1065123405691"
```

**Access context manager policy deleted:**

```
       Error: Error creating AccessLevel: googleapi: Error 404: Policy not found
       
         on .terraform/modules/shared.restricted_shared_vpc.access_level_members/modules/access_level/main.tf line 21, in resource "google_access_context_manager_access_level" "access_level":
         21: resource "google_access_context_manager_access_level" "access_level" {    
```

### CODE REVIEW

**Comment by daniel-cit** [comment]
It is not possible to solve the `"Concurrent change of peering network in step 4-projects"` using `depends_on` in the modules because the fixture code for step for uses the 8 `businessUnitN/env` folders as modules which makes terraform fail because each one has its own Google provider definition, which brakes `depends_on`:

```
tep #2 - "create":        Error: Module does not support depends_on
Step #2 - "create":        
Step #2 - "create":          on main.tf line 105, in module "projects_bu2_prod":
Step #2 - "create":         105:   source                           = "../../../4-projects/business_unit_2/production"
Step #2 - "create":        
Step #2 - "create":        Module "projects_bu2_prod" cannot be used with depends_on because it contains
Step #2 - "create":        a nested provider configuration for "google-beta", at
Step #2 - "create":        ../../../4-projects/business_unit_2/production/providers.tf:44,10-23.
Step #2 - "create":        
Step #2 - "create":        This module can be made compatible with depends_on by changing it to receive
Step #2 - "create":        all of its provider configurations from the calling module, by using the
Step #2 - "create":        "providers" argument in the calling module block.
Step #2 - "create":        
Step #2 - "create":        
Step #2 - "create":        Error: Module does not support depends_on
Step #2 - "create":        
Step #2 - "create":          on main.tf line 105, in module "projects_bu2_prod":
Step #2 - "create":         105:   source                           = "../../../4-projects/business_unit_2/production"
Step #2 - "create":        
Step #2 - "create":        Module "projects_bu2_prod" cannot be used with depends_on because it contains
Step #2 - "create":        a nested provider configuration for "google.impersonate", at
Step #2 - "create":        ../../../4-projects/business_unit_2/production/providers.tf:21,10-18.
Step #2 - "create":        
Step #2 - "create":        This module can be made compatible with depends_on by changing it to receive
Step #2 - "create":        all of its provider configurations from the calling module, by using the
Step #2 - "create":        "providers" argument in the calling module block.
Step #2 - "create":        
Step #2 - "create":        
Step #2 - "create":        Error: Module does not support depends_on
Step #2 - "create":        
Step #2 - "create":          on main.tf line 105, in module "projects_bu2_prod":
Step #2 - "create":         105:   source                           = "../../../4-projects/business_unit_2/production"
Step #2 - "create":        
Step #2 - "create":        Module "projects_bu2_prod" cannot be used with depends_on because it contains
Step #2 - "create":        a nested provider configuration for "google", at
Step #2 - "create":        ../../../4-projects/business_unit_2/production/providers.tf:40,10-18.
Step #2 - "create":        
Step #2 - "create":        This module can be made compatible with depends_on by changing it to receive
Step #2 - "create":        all of its provider configurations from the calling module, by using the
Step #2 - "create":        "providers" argument in the calling module block.
Step #2 - "create":        
```
 

to solve this it is probably necessary to split the fixture for `projects` in two steps, one for `bu1` and one for `bu2`

**Comment by daniel-cit** [comment]
One build failed because of this error:

```
       Error: Error enabling the Compute Engine API required to delete the default network: Error waiting for Enable Project "prj-bu2-d-env-secrets-92d7" Services: [compute.googleapis.com]: Error code 3, message: [service compute.googleapis.com encountered internal error: type: "googleapis.com" subject: "160009" ] with failed services [compute.googleapis.com] 
       
         on .terraform/modules/projects_bu2_dev.env_secrets_project.project/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
         65: resource "google_project" "main" {    
```

**Comment by bharathkkb** [comment]
@daniel-cit can we serialize following the approach done for networking https://github.com/terraform-google-modules/terraform-example-foundation/pull/298/commits/85dec2517f5990a8487f7b59c072934784a0dff5

**Review by bharathkkb — APPROVED** [review]
LGTM, looks like `request_timeout` has helped with the DNS errors

**Pull request merged**
