### PR TITLE
chore(tfvars): fix broken symlinks

### PR DESCRIPTION
**Pull request by eeaton**
Fix broken symlinks. Instructions on github are to replace all *.example.tfvars with *.tfvars. Most symlinks for tfvars correctly point to a the *.tfvars files, so that a user following the instructions as written does not need to modify any symlinks.

A small number of files have symlinks to point to *.example.tfvars, which causes deployment errors related to undefined variables and requires troubleshooting to identify and fix. I've corrected these broken symlinks.

### CODE REVIEW

**Review by daniel-cit — APPROVED** [review]
LGTM

**Review by fmichaelobrien — APPROVED** [review]
/lgtm
Very nice - thanks for this, I am doing a 2nd clean org deploy this week and will reverify

**Review by apeabody — APPROVED** [review]
Thanks @eeaton! LGTM

**Comment by mariammartins** [comment]
gcbrun

**Pull request merged**
