### PR TITLE
fix: #1229 - fix 3-nhas symlinks

### PR DESCRIPTION
**Pull request by fmichaelobrien**
see testing on #1229 
## 3-networks-hub-and-spoke
- 2 symlinks modified in error during the non-production to nonproduction rename/refactor - the change is to ../common - which itself is a symlink so the double symlink works.  The other 6 of the 2x4 symlinks are unmodified as ../../
see change in #1107
https://github.com/terraform-google-modules/terraform-example-foundation/pull/1107/files#diff-bcfdfb477dea3f75d9d515aa61ce4f3836b223f11d6e4234122778963fbfef4a

https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks-hub-and-spoke/envs/nonproduction/access_context.auto.tfvars
```
-../../access_context.auto.tfvars
+../shared/access_context.auto.tfvars
```
there is a 2nd symlink regression in the same directory in 
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks-hub-and-spoke/envs/nonproduction/common.auto.tfvars
```
-../../common.auto.tfvars
+../shared/common.auto.tfvars
```
I'll raise an issue shortly with the fix after I test a full upstream sync of the TEF.

Screenshot 2024-05-11 at 19 09 03

### CODE REVIEW

**Review by daniel-cit — APPROVED** [review]
LGTM

**Comment by fmichaelobrien** [comment]
either of #1233 
or #1230 

can go in - they are the same fix

**Comment by fmichaelobrien** [comment]
Daniel, myself and the team - really appreciate the speed that this PR was reviewed - thank you
For gcbrun - Looking into the build issues - looks quota related - will retry

**Comment by daniel-cit** [comment]
@fmichaelobrien could you please update the PR with the base branch?

**Comment by fmichaelobrien** [comment]
Will do, eta 30 min...

**Comment by fmichaelobrien** [comment]
updated
https://github.com/CloudLandingZone/terraform-example-foundation/tree/gh1229-fix-symlinks

pulled in yesterday's https://github.com/terraform-google-modules/terraform-example-foundation/commit/87179633f1ed238575a5d76dc3b152a0a3dc945d

**Comment by eeaton** [comment]
@fmichaelobrien we've had a few concurrent PRs that have put this one out-of-date with base branch, but if you sync it I'll re-trigger the CI tests and merge now. (will hold off on a few other PR until this one passes)

**Comment by fmichaelobrien** [comment]
Syncing now - eta 10 min

**Comment by obriensystems** [comment]
sync complete - no merge conflicts on https://github.com/CloudLandingZone/terraform-example-foundation/tree/gh1229-fix-symlinks

**Review by eeaton — APPROVED** [review]

**Pull request merged**
