### PR TITLE
fix: github actions upgrade

### PR DESCRIPTION
**Pull request by lpezet**
The following upgrades were made in github workflow files:

- actions/checkout@v3 --> **actions/checkout@v4**

https://github.com/actions/checkout/blob/main/CHANGELOG.md

```
v4.1.7
Bump the minor-npm-dependencies group across 1 directory with 4 updates by @dependabot in #1739
Bump actions/checkout from 3 to 4 by @dependabot in #1697
Check out other refs/* by commit by @orhantoy in #1774
Pin actions/checkout's own workflows to a known, good, stable version. by @jww3 in #1776

v4.1.6
Check platform to set archive extension appropriately by @cory-miller in #1732

v4.1.5
Update NPM dependencies by @cory-miller in #1703
Bump github/codeql-action from 2 to 3 by @dependabot in #1694
Bump actions/setup-node from 1 to 4 by @dependabot in #1696
Bump actions/upload-artifact from 2 to 4 by @dependabot in #1695
README: Suggest user.email to be 41898282+github-actions[bot]@users.noreply.github.com by @cory-miller in #1707

v4.1.4
Disable extensions.worktreeConfig when disabling sparse-checkout by @jww3 in #1692
Add dependabot config by @cory-miller in #1688
Bump the minor-actions-dependencies group with 2 updates by @dependabot in #1693
Bump word-wrap from 1.2.3 to 1.2.5 by @dependabot in #1643

v4.1.3
Check git version before attempting to disable sparse-checkout by @jww3 in #1656
Add SSH user parameter by @cory-miller in #1685
Update actions/checkout version in update-main-version.yml by @jww3 in #1650

v4.1.2
Fix: Disable sparse checkout whenever sparse-checkout option is not present @dscho in #1598

v4.1.1
Correct link to GitHub Docs by @peterbe in #1511
Link to release page from what's new section by @cory-miller in #1514

v4.1.0
Add support for partial checkout filters

v4.0.0
Support fetching without the --progress option
Update to node20
```

- google-github-actions/auth@v1 --> **google-github-actions/auth@v2**

https://github.com/google-github-actions/auth/releases

https://github.com/google-github-actions/auth/releases/tag/v2.0.0
https://github.com/google-github-actions/auth/releases/tag/v2.0.1
https://github.com/google-github-actions/auth/releases/tag/v2.1.0
https://github.com/google-github-actions/auth/releases/tag/v2.1.1
https://github.com/google-github-actions/auth/releases/tag/v2.1.2
https://github.com/google-github-actions/auth/releases/tag/v2.1.3

- google-github-actions/setup-gcloud@v1 --> **google-github-actions/setup-gcloud@v2**

https://github.com/google-github-actions/setup-gcloud/releases

https://github.com/google-github-actions/setup-gcloud/releases/tag/v2.0.0
https://github.com/google-github-actions/setup-gcloud/releases/tag/v2.0.1
https://github.com/google-github-actions/setup-gcloud/releases/tag/v2.1.0

- hashicorp/setup-terraform@v2 --> **hashicorp/setup-terraform@v3**

https://github.com/hashicorp/setup-terraform/blob/main/CHANGELOG.md

```
3.1.1 (2024-05-07)
BUG FIXES:
wrapper: Fix wrapper to output to stdout and stderr immediately when data is received (#395)

3.1.0 (2024-04-23)
ENHANCEMENTS:
Automatically fallback to darwin/amd64 for Terraform versions before 1.0.2 as releases for darwin/arm64 are not available (#409)

3.0.0 (2023-10-30)
NOTES:
Updated default runtime to node20 (#346)
The wrapper around the installed Terraform binary has been fixed to return the exact STDOUT and STDERR from Terraform when executing commands. Previous versions of setup-terraform may have required workarounds to process the STDOUT in bash, such as filtering out the first line or selectively parsing STDOUT with jq. These workarounds may need to be adjusted with v3.0.0, which will now return just the STDOUT/STDERR from Terraform with no errant characters/statements. (#367)
BUG FIXES:
Fixed malformed stdout when wrapper is enabled (#367)
```

### CODE REVIEW

**Review by Natthachai0434 — COMMENTED** [review]
Nice!!

**Review by Natthachai0434 — APPROVED** [review]

**Comment by daniel-cit** [comment]
build is failing due to unrelated issues

```
Step #7 - "converge-org": Error: Provider produced inconsistent final plan
Step #7 - "converge-org": 
Step #7 - "converge-org": When expanding the plan for
Step #7 - "converge-org": module.cai_monitoring.module.cloud_function.google_cloudfunctions2_function.function
Step #7 - "converge-org": to include new values learned so far during apply, provider
Step #7 - "converge-org": "registry.terraform.io/hashicorp/google" produced an invalid new value for
Step #7 - "converge-org": .service_config[0].environment_variables: was null, but now
Step #7 - "converge-org": cty.MapVal(map[string]cty.Value{"LOG_EXECUTION_ID":cty.StringVal("true"),
Step #7 - "converge-org": "ROLES":cty.StringVal("roles/owner,roles/editor,roles/resourcemanager.organizationAdmin,roles/compute.networkAdmin,roles/compute.orgFirewallPolicyAdmin"),
Step #7 - "converge-org": "SOURCE_ID":cty.StringVal("organizations/REDACTED/sources/7635735894760282610")}).
Step #7 - "converge-org": 
Step #7 - "converge-org": This is a bug in the provider, which should be reported in the provider's own
Step #7 - "converge-org": issue tracker.
Step #7 - "converge-org": 
Step #7 - "converge-org": Error: Error creating OrganizationFeed: googleapi: Error 404: Requested entity was not found.
Step #7 - "converge-org": 
Step #7 - "converge-org":   with module.cai_monitoring.google_cloud_asset_organization_feed.organization_feed,
Step #7 - "converge-org":   on ../../modules/cai-monitoring/main.tf line 107, in resource "google_cloud_asset_organization_feed" "organization_feed":
Step #7 - "converge-org":  107: resource "google_cloud_asset_organization_feed" "organization_feed" {
Step #7 - "converge-org": }
Step #7 - "converge-org":     apply.go:34: 
Step #7 - "converge-org":         	Error Trace:	/builder/home/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.16/modules/terraform/apply.go:34
Step #7 - "converge-org":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.0/pkg/tft/terraform.go:571
Step #7 - "converge-org":         	            				/workspace/test/integration/org/org_test.go:101
Step #7 - "converge-org":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.0/pkg/tft/terraform.go:630
Step #7 - "converge-org":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.0/pkg/tft/terraform.go:669
Step #7 - "converge-org":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.0/pkg/utils/stages.go:31
Step #7 - "converge-org":         	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.0/pkg/tft/terraform.go:669
Step #7 - "converge-org":         	Error:      	Received unexpected error:
Step #7 - "converge-org":         	            	FatalError{Underlying: error while running command: exit status 1; 
Step #7 - "converge-org":         	            	Error: Provider produced inconsistent final plan
Step #7 - "converge-org":         	            	
Step #7 - "converge-org":         	            	When expanding the plan for
Step #7 - "converge-org":         	            	module.cai_monitoring.module.cloud_function.google_cloudfunctions2_function.function
Step #7 - "converge-org":         	            	to include new values learned so far during apply, provider
Step #7 - "converge-org":         	            	"registry.terraform.io/hashicorp/google" produced an invalid new value for
Step #7 - "converge-org":         	            	.service_config[0].environment_variables: was null, but now
Step #7 - "converge-org":         	            	cty.MapVal(map[string]cty.Value{"LOG_EXECUTION_ID":cty.StringVal("true"),
Step #7 - "converge-org":         	            	"ROLES":cty.StringVal("roles/owner,roles/editor,roles/resourcemanager.organizationAdmin,roles/compute.networkAdmin,roles/compute.orgFirewallPolicyAdmin"),
Step #7 - "converge-org":         	            	"SOURCE_ID":cty.StringVal("organizations/REDACTED/sources/7635735894760282610")}).
Step #7 - "converge-org":         	            	
Step #7 - "converge-org":         	            	This is a bug in the provider, which should be reported in the provider's own
Step #7 - "converge-org":         	            	issue tracker.
Step #7 - "converge-org":         	            	
Step #7 - "converge-org":         	            	Error: Error creating OrganizationFeed: googleapi: Error 404: Requested entity was not found.
Step #7 - "converge-org":         	            	
Step #7 - "converge-org":         	            	  with module.cai_monitoring.google_cloud_asset_organization_feed.organization_feed,
Step #7 - "converge-org":         	            	  on ../../modules/cai-monitoring/main.tf line 107, in resource "google_cloud_asset_organization_feed" "organization_feed":
Step #7 - "converge-org":         	            	 107: resource "google_cloud_asset_organization_feed" "organization_feed" {
Step #7 - "converge-org":         	            	}
Step #7 - "converge-org":         	Test:       	TestOrg
Step #7 - "converge-org": 2024/07/23 14:02:02 RUN_STAGE env var set to apply
Step #7 - "converge-org": 2024/07/23 14:02:02 Skipping stage teardown
Step #7 - "converge-org": --- FAIL: TestOrg (540.22s)
Step #7 - "converge-org": FAIL
Step #7 - "converge-org": FAIL	github.com/terraform-google-modules/terraform-example-foundation/test/integration/org	540.275s
Step #7 - "converge-org": FAIL
Step #7 - "converge-org": t=2024-07-23T14:02:02+0000 lvl=eror msg="error running command: exit status 1"

```

**Review by eeaton — APPROVED** [review]

**Pull request merged**
