### PR TITLE
feat: Change old firewall to new network-firewall

### PR DESCRIPTION
**Pull request by Samir-Cit**
Hello folks.

This PR is to change all compute firewall resources ([google_compute_firewall](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall)) to the new network firewall resource ([google_compute_network_firewall_policy_rule](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy_rule)) using the module ([terraform-google-modules/network/google//modules/network-firewall-policy](https://registry.terraform.io/modules/terraform-google-modules/network/google/latest/submodules/network-firewall-policy))

This **network firewall policy** module will:
- Create a Firewall Policy
- Create a Firewall Policy Association between the Firewall Policy and the VPC network
- Create the Firewall Policy Rules linked to the Firewall Policy.

### CODE REVIEW

**Review by lanre-OG — APPROVED** [review]
LGTM

**Review by jasonbisson — COMMENTED** [review]
The code LGTM, but integration tests are still failing.

**Review by rjerrems — APPROVED** [review]

**Review by gtsorbo — APPROVED** [review]
LGTM

**Comment by daniel-cit** [comment]
@gtsorbo @apeabody @bharathkkb @rjerrems 
Approve PR is green 🎉

**Pull request merged**
