### PR TITLE
actually enable data access logs collection

### PR DESCRIPTION
**Pull request by umairidris**
This is required for HIPAA alignment.

### CODE REVIEW

**Comment by daniel-cit** [comment]
Thanks for catching this.

The example foundation can be deployed in the organization or in a folder, so two resource blocks with the same settings could be added, one for the organization deploy and one for the folder deploy:

```
resource "google_organization_iam_audit_config" "organization_config" {
  count   = var.data_access_logs_enabled && var.parent_folder == "" ? 1 : 0
  org_id  = var.org_id
  service = "allServices"
...
```

```
resource "google_folder_iam_audit_config" "folder_config" {
  count   = var.data_access_logs_enabled && var.parent_folder != "" ? 1 : 0
  folder  = "folders/${var.parent_folder}"
  service = "allServices"
...
```

**Comment by umairidris** [comment]
Done, thanks!

**Comment by bharathkkb** [comment]
@daniel-cit Was there a reason why we removed this with https://github.com/terraform-google-modules/terraform-example-foundation/pull/94?

**Comment by daniel-cit** [comment]
@bharathkkb It was incorrectly removed in the large refactor in the logging part.

**Review by bharathkkb — APPROVED** [review]
LGTM and I think this is one that Andy mentioned today @daniel-cit 
/cc @rjerrems

**Pull request merged**
