### PR TITLE
Removes filter for sinks

### LINKED ISSUE #258: [shascanner] LOG_NOT_EXPORTED detected
LOG_NOT_EXPORTED is detected because log sinks are created with 
    logName: /logs/cloudaudit.googleapis.com%2Factivity OR
    logName: /logs/cloudaudit.googleapis.com%2Fsystem_event OR
    logName: /logs/cloudaudit.googleapis.com%2Fdata_access OR
    logName: /logs/compute.googleapis.com%2Fvpc_flows OR
    logName: /logs/compute.googleapis.com%2Ffirewall OR
    logName: /logs/cloudaudit.googleapis.com%2Faccess_transparency

And the detector considers that the sink should have an empty filter to log every possible log created.

Changes sink creation to use a empty filter.

### PR DESCRIPTION
**Pull request by amandakarina**
Hey folks

This pull request closes #258 issue.

Could you, please, take a look?

Thanks!

### CODE REVIEW

**Comment by rjerrems** [comment]
Hi @amandakarina - would be good to understand some extra context on what we are trying to achieve here, I have commented on the linked bug

**Comment by amandakarina** [comment]
> Hi @amandakarina - would be good to understand some extra context on what we are trying to achieve here, I have commented on the linked bug

Hey @rjerrems 
The SHA scanner detected this finding after deploy CFT in a clean organization. The SHA Scanner checks if the sink has a empty filter, if so, no finding is generated, otherwise, a LOG_NOT_EXPORTED finding is created.

**Comment by rjerrems** [comment]
Yep - I suppose the question I have is: are we recommending that people export *all* logs? Are we confident the SHA finding is representative of best practice here? It doesn't seem to stack up with my experience where specific log types are usually targeted. It will also increase cost, particularly in our case where we are creating three copies of the exported logs to GCS, BigQuery & PubSub.

**Comment by amandakarina** [comment]
Hey @rjerrems, I remove the filter only for bucket export. Could you, please take a look?

**Comment by rjerrems** [comment]
Thanks @amandakarina - can we add some brief docs that explain the difference, then we should be good to go.

Just to confirm also, that the SHA scanner result is fixed by this change?

**Comment by amandakarina** [comment]
> Thanks @amandakarina - can we add some brief docs that explain the difference, then we should be good to go.
> 
> Just to confirm also, that the SHA scanner result is fixed by this change?

Hey Rohan!

Based on my test, yes!
I inactivated all findings for LOG_NOT_EXPORTED and create a new project under my folder.
After SHA Scanner was executed no new finding was created and no finding for my folder was re-activated.

**Review by rjerrems — APPROVED** [review]
LGTM

**Comment by rjerrems** [comment]
FYI Merging because test failure is due to name collision & healthy test run on prior commit

**Pull request merged**
