### PR TITLE
added Shielded VMs constraint

### PR DESCRIPTION
**Pull request by daniel-cit**
Add [Shielded VMs](https://cloud.google.com/security/shielded-cloud/shielded-vm) constraint to the list of org policies

### CODE REVIEW

**Review by bharathkkb — APPROVED** [review]
LGTM

**Comment by rjerrems** [comment]
Do we know what the impact of applying this policy is for service that launch VMs in the customer project? e.g Dataflow, Composer etc - do these services support shielded VMs?

**Comment by bharathkkb** [comment]
@rjerrems good catch, both don't seem supported. Perhaps we should move this to a note like are doing for `oslogin`.

**Comment by rjerrems** [comment]
Yeah I think that might be worthwhile, otherwise customers will be knee deep in project exemptions to use a number of services.(although some customers may want this)

**Comment by daniel-cit** [comment]
New PR create for develop branch with TF 0.13

**Pull request closed without merging**
