### PR TITLE
feat: add instructions for deployment using GitLab pipelines

### PR DESCRIPTION
**Pull request by daniel-cit**
This pull request adds support for deployment of the terraform Example Foundation using Gitlab pipelines

### CODE REVIEW

**Review by gtsorbo — APPROVED** [review]
LGTM

**Comment by daniel-cit** [comment]
@apeabody @gtsorbo @bharathkkb approved PR is Green 🎉

**Comment by daniel-cit** [comment]
@apeabody @bharathkkb @gtsorbo approved PR is Green 🎉 🎉

**Pull request merged**
