### PR TITLE
feat!: Enable CMEK for Terraform state buckets

### PR DESCRIPTION
**Pull request by daniel-cit**
This PR enables Customer-managed encryption keys ([CMEK](https://cloud.google.com/kms/docs/cmek)) in the Google Cloud Storage Buckets created in the `0-bootstrap` step to host Terraform state data.

### CODE REVIEW

**Review by rjerrems — APPROVED** [review]

**Comment by daniel-cit** [comment]
@gtsorbo @apeabody 
The Build is Green 🎉

**Pull request merged**
