### PR TITLE
feat: Add Provider cache

### PR DESCRIPTION
**Pull request by bharathkkb**
Local tests:
- time to validate without bundle: `25m`. dir size: `5.2GB`
- time to validate with bundle: `11m`. dir size: `400MB`
- time to validate with bundle and parallel: `5m`. dir size: `400MB`

Cloud build:
- time to validate without bundle: ~ `7m`
- time to validate with bundle and parallel: `2m`

ref: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/773

### CODE REVIEW

**Comment by rjerrems** [comment]
are we still looking at doing this @bharathkkb ?

**Comment by bharathkkb** [comment]
@rjerrems should be ready, I just have to backport this feature to a 0.12 image.

**Comment by bharathkkb** [comment]
@rjerrems this is ready for review. With the 0.12.2 image, we also update the tfdocs to 0.10.1 so there are some diffs from that. Core changes are https://github.com/terraform-google-modules/terraform-example-foundation/pull/250/commits/2ccb029b7187ec1b848daeb6723d94c401e54e39, doc updates are https://github.com/terraform-google-modules/terraform-example-foundation/pull/250/commits/0796b0a8b4d9eae5136e76bd7120cdb5ee43d469

**Comment by rjerrems** [comment]
Cool looks good @bharathkkb - once we can confirm integration tests are running cleanly should be good to merge

**Comment by rjerrems** [comment]
Looks like we have merge conflicts now @bharathkkb - happy to merge once those are fixed :)

**Review by rjerrems — APPROVED** [review]
LGTM

**Pull request merged**
