### PR TITLE
fix: Add roles and service enablements to bootstrap project

### PR DESCRIPTION
**Pull request by obriensystems**
## Overview

  This PR is an initial canary PR that addresses a couple minor service enablement and IAM role requirements during the 0-bootstrap and 1-org subsections that occurred on a clean GCP organization when following the readme instructions deploying the landing zone.
  We as a team would like to also determine the formal process ( #1179 ) around PR submission as we add more ER or Bug PRs while we bring up the as-is TEF deployment for future additional functionality
    

see testing in https://github.com/terraform-google-modules/terraform-example-foundation/issues/1133
specifically

https://github.com/terraform-google-modules/terraform-example-foundation/issues/1136
https://github.com/terraform-google-modules/terraform-example-foundation/issues/1139
https://github.com/terraform-google-modules/terraform-example-foundation/issues/1140
https://github.com/terraform-google-modules/terraform-example-foundation/issues/1142
https://github.com/terraform-google-modules/terraform-example-foundation/issues/1143
https://github.com/terraform-google-modules/terraform-example-foundation/issues/1161

## Guidance
This first PR is a preliminary fix for service enablements and roles required during bootstrap of the TEF deployment.
Later in #1144 the readme instructions will be added to a bootstrap.sh script

### CODE REVIEW

**Comment by fmichaelobrien** [comment]
Going through PR approval procedures to the readme in
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/CONTRIBUTING.md

specifically how to request review time from the https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/CODEOWNERS

reference: #1179

**Comment by fmichaelobrien** [comment]
Merge in group creation fixes in https://github.com/CloudLandingZone/terraform-example-foundation/compare/gh1133-bootstrap-1136...terraform-google-modules%3Aterraform-example-foundation%3Amaster
to https://github.com/CloudLandingZone/terraform-example-foundation/tree/gh1133-bootstrap-1136

**Comment by fmichaelobrien** [comment]
Lint ran - fixing whitespace issues in another commit
https://github.com/terraform-google-modules/terraform-example-foundation/actions/runs/8557468090/job/23449822771?pr=1175
```
Error: The following tests have failed: check_whitespace
```

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21

**Comment by obriensystems** [comment]
I'll raise in a separate PR but 3-networks-hub-and-spoke also needs the compute.orgSecurityPolicyAdmin or User IAM role on the super admin to be able to view Hierarchical Firewall Policies created under the common branch

**Review by eeaton — APPROVED** [review]

**Comment by eeaton** [comment]
Thanks for the submission, for the additional roles are LGTM. Can you re-sync the branch?

**Comment by obriensystems** [comment]
sounds good,  there are additional sections in the gitlab, github, jenkins build variants that i will separately test/pr later.
i will rebase this branch for the CB/CSR default..

**Comment by fmichaelobrien** [comment]
main branch merged - waiting on "lint" task report...

**Comment by fmichaelobrien** [comment]
Thank you TEF team - we really appreciate this initial PR!!!
We will be moving over select changes from our fork over the next 4-8 weeks that benefit the wider TEF community.

**Pull request merged**
