### PR TITLE
Move SCR definition to variables.

### PR DESCRIPTION
**Pull request by jaroslawgajewski**
Move SCR definition to variables.

### CODE REVIEW

**Review by bharathkkb — CHANGES_REQUESTED** [review]
Hi @jaroslawgajewski 
Thanks for the PR! Could you also regenerate docs  by running `make docker_generate_docs`

**Comment by jaroslawgajewski** [comment]
Hi @bharathkkb 
I've regenerated documentation again but still failing for lint checks. Can you have a look what is  that related to? I was trying to remove HTLM entries from readme manually but it seem scripts are putting it back during doc generation.

**Comment by rjerrems** [comment]
Hi @jaroslawgajewski - it looks like you need to run a `terraform fmt`

```
gcr.io/cloud-foundation-cicd/cft/developer-tools:0.13
Checking for documentation generation
Checking for trailing whitespace
Checking for missing newline at end of file
Running shellcheck
Checking file headers
Running flake8
Attempting to download /workspace/test/bundle.hcl bundle.
/tmp/bundler /workspace
Failed to read config: At 6:12: root.providers.google: not an object type for struct (*ast.ListType)
unzip: can't open terraform_*.zip[.zip]
/workspace
Running terraform fmt
0-bootstrap/variables.tf
--- old/0-bootstrap/variables.tf
+++ new/0-bootstrap/variables.tf
@@ -78,7 +78,7 @@
 variable "cloud_source_repos" {
   description = "List of Cloud Source Reposiories created during bootrstap project build stage"
   type        = list(string)
-  default     = ["gcp-bootstrap","gcp-org","gcp-environments","gcp-networks","gcp-projects"]
+  default     = ["gcp-bootstrap", "gcp-org", "gcp-environments", "gcp-networks", "gcp-projects"]
 }
 
 /* ----------------------------------------
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
```

Also FYI, you can run linting yourself locally by running `make docker_test_lint`

**Review by bharathkkb — APPROVED** [review]

**Review by rjerrems — APPROVED** [review]

**Pull request merged**
