### PR TITLE
chore: remove unused tfvars

### PR DESCRIPTION
**Pull request by nbugden**
Remove unused tfvars that were removed in this commit: https://github.com/terraform-google-modules/terraform-example-foundation/commit/f57a47c2e36e9924a3232983385e741fd05ee2f3#diff-772cebf2058d9fd66a2fd923eb13802b5a561daff7c66d1950d19675a3aa93f1

### CODE REVIEW

**Review by obriensystems — APPROVED** [review]
/lgtm

**Comment by nbugden** [comment]
@rjerrems @eeaton @gtsorbo can one of you folks take a look. PR needs `/gcbrun` and an approving review.

**Comment by nbugden** [comment]
> @rjerrems @eeaton @gtsorbo can one of you folks take a look. PR needs `/gcbrun` and an approving review.

Nudge, can I get a review. If there is something else required before review, please let me know.

**Review by fmichaelobrien — APPROVED** [review]
/lgtm
I ran into these warnings during 1133 - thank you for fixing

**Review by eeaton — APPROVED** [review]

**Comment by eeaton** [comment]
/gcbrun

Thanks for the submission!

**Comment by nbugden** [comment]
> /gcbrun
> 
> Thanks for the submission!

Thanks @eeaton looks like it needs /gcbrun again. I just pulled in the latest changes from master.

**Comment by nbugden** [comment]
@eeaton checks have passed. Ready to be merge, but I'm not authorized.

**Comment by nbugden** [comment]
Looks like this time both cloud build checks failed. I can't see the failures. I also had to pull in the latest changes. Can you help me with the error so I can address any changes needed in the PR?

**Comment by eeaton** [comment]
@nbugden  The CI tests that do a complete build of the foundation have been failing with a high frequency of flaky errors that don't seem to have anything to do with the proposed changes. (I'm getting stuck on several other PR with small tweaks as well). A few PR have managed to pass for the small %age of times that the CI runs without errors, so it's worth trying to re-run a few times, but I'm also in the process of trying to improve the reliability of tests.

**Comment by nbugden** [comment]
Needs /gcbrun again

**Comment by nbugden** [comment]
Checks are still failing... needs to be rerun

**Comment by nbugden** [comment]
Check have passed... can someone merge?

**Comment by nbugden** [comment]
@eeaton my branch is behind the renovate bot changes... auto-merge is not being triggered. If I pull in the latest it will clear the auto-merge and force the pipelines to run again.

**Pull request merged**
