### PR TITLE
feat: create projects for KMS resources

### PR DESCRIPTION
**Pull request by daniel-cit**
This PR creates projects for Cloud Key Management Service (KMS) resources at org level and at environment level independently of the secrets projects for better separation of concerns related to the Secret Manager.

### CODE REVIEW

**Review by lanre-OG — APPROVED** [review]
LGTM

**Review by gtsorbo — APPROVED** [review]
LGTM

**Comment by daniel-cit** [comment]
@gtsorbo @apeabody @bharathkkb Approved build is finally green 🎉

**Pull request merged**
