### PR TITLE
doc: Add note on billing quota exceeded

### LINKED ISSUE #269: Adds docs around possible billing quota issue
In addition to [project quota documented,](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites) users may hit billing quota issue and it is surfaced with an error message like so
```
Error: Error setting billing account "<billing account id>" for project "projects/foo": googleapi: Error 400: Precondition check failed., failedPrecondition
```
To confirm if this is indeed the issue, we can manually try this
```
gcloud alpha billing projects link foo --billing-account XXXXXX-XXXXXX-XXXXXX
```
which will surface a quota issue and users have to request increase via https://support.google.com/code/contact/billing_quota_increase

x-ref: https://github.com/terraform-google-modules/terraform-google-project-factory/issues/28#issuecomment-422178737

### PR DESCRIPTION
**Pull request by vovinacci**
This PR adds note on possible exceeded billing quota (I've experienced it myself) to document this issue before troubleshooting guide will be in place.

Closes #269

### CODE REVIEW

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @vovinacci 
I was thinking of keeping this next to the other quota error here: https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites

**Comment by vovinacci** [comment]
@bharathkkb I can move it there as well. Main reason, having it there was is that you most likely hit it with shiny new organisation on that step. Anyway, will move it there now.

**Comment by bharathkkb** [comment]
@vovinacci totally agree. We are looking into creating a whole new troubleshooting guide for our v2 release and may move this there.

**Review by bharathkkb — APPROVED** [review]
LGTM
/cc @rjerrems; tracking overall guide #291

**Pull request merged**
