### PR TITLE
fix: add network fixture prepare to lint test

### PR DESCRIPTION
**Pull request by bharathkkb**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Attempting to download /workspace/test/bundle.hcl bundle.
/tmp/bundler /workspace
Fetching Terraform 0.13.5 core package...
Local plugin directory ".plugins" found; scanning for provider binaries.
No ".plugins" directory found, skipping local provider discovery.
Creating terraform_0.13.5-bundle2021020322_linux_amd64.zip ...
All done!
Archive:  terraform_0.13.5-bundle2021020322_linux_amd64.zip
/workspace
Running terraform fmt
Running terraform validate
terraform_validate ./0-bootstrap 
Success!
 The configuration is valid.
terraform_validate ./0-bootstrap/modules/jenkins-agent 
Success!
 The configuration is valid.
terraform_validate ./1-org/envs/shared 
Success!
 The configuration is valid.
terraform_validate ./2-environments/envs/development 
Success!
 The configuration is valid.
terraform_validate ./2-environments/envs/non-production 
Success!
 The configuration is valid.
terraform_validate ./2-environments/envs/production 
Success!
 The configuration is valid.
terraform_validate ./2-environments/modules/env_baseline 
Success!
 The configuration is valid.
terraform_validate ./3-networks/envs/development 
Success!
 The configuration is valid.
terraform_validate ./3-networks/envs/non-production 
Success!
 The configuration is valid.
terraform_validate ./3-networks/envs/production 
Success!
 The configuration is valid.
terraform_validate ./3-networks/envs/shared 
Success!
 The configuration is valid.
terraform_validate ./3-networks/modules/base_shared_vpc 
Success!
 The configuration is valid.
terraform_validate ./3-networks/modules/dedicated_interconnect 
Success!
 The configuration is valid.
terraform_validate ./3-networks/modules/restricted_shared_vpc 
Success!
 The configuration is valid.
terraform_validate ./3-networks/modules/vpn-ha 
Success!
 The configuration is valid.
terraform_validate ./4-projects/business_unit_1/development 
Success!
 The configuration is valid.
terraform_validate ./4-projects/business_unit_1/non-production 
Success!
 The configuration is valid.
terraform_validate ./4-projects/business_unit_1/production 
Success!
 The configuration is valid.
terraform_validate ./4-projects/business_unit_2/development 
Success!
 The configuration is valid.
terraform_validate ./4-projects/business_unit_2/non-production 
Success!
 The configuration is valid.
terraform_validate ./4-projects/business_unit_2/production 
Success!
 The configuration is valid.
terraform_validate ./4-projects/modules/single_project 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/bootstrap 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/envs 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/networks 
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: 
Module does not support depends_on
  on main.tf line 30, in module "non-production":
  30:   source                           = 
"../../../3-networks/envs/non-production"
Module "non-production" cannot be used with depends_on because it contains a
nested provider configuration for "google.impersonate", at
../../../3-networks/envs/non-production/providers.tf:21,10-18.
This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
Error: 
Module does not support depends_on
  on main.tf line 30, in module "non-production":
  30:   source                           = 
"../../../3-networks/envs/non-production"
Module "non-production" cannot be used with depends_on because it contains a
nested provider configuration for "google", at
../../../3-networks/envs/non-production/providers.tf:40,10-18.
This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
Error: 
Module does not support depends_on
  on main.tf line 30, in module "non-production":
  30:   source                           = 
"../../../3-networks/envs/non-production"
Module "non-production" cannot be used with depends_on because it contains a
nested provider configuration for "google-beta", at
../../../3-networks/envs/non-production/providers.tf:45,10-23.
This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
Error: 
Module does not support depends_on
  on main.tf line 43, in module "production":
  43:   source                           = 
"../../../3-networks/envs/production"
Module "production" cannot be used with depends_on because it contains a
nested provider configuration for "google.impersonate", at
../../../3-networks/envs/production/providers.tf:21,10-18.
This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
Error: 
Module does not support depends_on
  on main.tf line 43, in module "production":
  43:   source                           = 
"../../../3-networks/envs/production"
Module "production" cannot be used with depends_on because it contains a
nested provider configuration for "google", at
../../../3-networks/envs/production/providers.tf:40,10-18.
This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
Error: 
Module does not support depends_on
  on main.tf line 43, in module "production":
  43:   source                           = 
"../../../3-networks/envs/production"
Module "production" cannot be used with depends_on because it contains a
nested provider configuration for "google-beta", at
../../../3-networks/envs/production/providers.tf:45,10-23.
This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
terraform_validate ./test/fixtures/org 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/projects 
Success!
 The configuration is valid.
terraform_validate ./test/setup 
Success!
 The configuration is valid.
 ```

**Review by rjerrems — APPROVED** [review]
LGTM

**Comment by rjerrems** [comment]
@bharathkkb I think we will need to do something about this as only one can exist at a time and will cause tests to fail

```Error: Error creating Policy: googleapi: Error 409: The resource 'entity.policy' named 'dp-p-shared-base-default-policy' already exists, alreadyExists```

I have re-run the one failed build 🤞

**Comment by bharathkkb** [comment]
@rjerrems  That is odd, from the logs I don't see any other `dp-p-shared-base-default-policy` being created either. It was created in default mode test but IIUC this resource is namespaced to the project `projects/tst-p-shared-base-xxxx/policies/dp-p-shared-base-default-policy`

**Pull request merged**
