### PR TITLE
feat: add terraform show command to wrapper script

### LINKED ISSUE #259: Add a show command in tf-wrapper.sh
Right now tf-wrapper.sh supports running the commands `init`, `plan`, `apply` and `validate`.

Validate makes a call to `terraform show` to output the plan as JSON for validation, however, there is no option to directly call `show` ourselves. 

Adding the show command would allow us to output the plan in a human-friendly format for inspection before merging on an environment branch. We could then post the output in a PR/MR comment for example.

What do you think?

### PR DESCRIPTION
**Pull request by fparga**
Add a `show` command to `tf-wrapper.sh`.

Closes #259

### CODE REVIEW

**Comment by rjerrems** [comment]
Thanks @fparga - it looks like linting tests are failing with the following:

```
Checking for trailing whitespace
./build/tf-wrapper.sh:172:          
Error: Trailing whitespace found in the lines above
```

**Comment by fparga** [comment]
@rjerrems I fixed the linting issue but it looks like the integration tests are failing now

**Comment by rjerrems** [comment]
I have re-triggered those tests, but otherwise LGTM. Thanks!

**Review by bharathkkb — APPROVED** [review]
LGTM

**Pull request merged**
