### PR TITLE
fix: 3-networks-hub-and-spoke Deploying with Cloud Build step 9 fails (#1045)

### PR DESCRIPTION
**Pull request by moszutij**
This PR resolves issue #1045

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @moszutij!

For clarity/safety, let's bump https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks-hub-and-spoke/modules/base_shared_vpc/main.tf#L30 to `"~> 7.2"`

The lint CI should just need a `terraform fmt` on the listed files.

**Comment by moszutij** [comment]
@apeabody thanks for your inputs!

**Comment by moszutij** [comment]
Aligned subnet type definition with https://registry.terraform.io/modules/terraform-google-modules/network/google/7.2.0/submodules/subnets. The subnet_flow_logs value should now be correctly supplied to the subnet sub module to activate the network flow logs while adhering to the security foundation's organisational policies.

**Pull request closed without merging**
