### PR TITLE
Dedicated Interconnect update

### PR DESCRIPTION
**Pull request by daniel-cit**
In this change:

- Adds candidate subnetworks to each VLAN attachment
- move commented Dedicated Interconnect code to a interconnect.tf.example file in each environment folder
- Update the READMEs

### CODE REVIEW

**Comment by daniel-cit** [comment]
@mikelaramie Cloud you please take a look at these changes?

**Comment by mikelaramie** [comment]
@daniel-cit the other option we should add is [vlan_tag8021q](https://www.terraform.io/docs/providers/google/r/compute_interconnect_attachment.html#vlan_tag8021q), similar to the `candidate_subnets` Example:
`region1_router1_vlan_tag8021q="1234"` in interconnect.tf 
and 
`vlan_tag8021q = var.region1_router1_vlan_tag8021q` in the `interconnect_attachment1_region1` module

If the values are null, they should be auto-generated by the interconnect; I'll test that out as well.

**Comment by mikelaramie** [comment]
Code changes lgtm!

**Comment by rjerrems** [comment]
LGTM - once we have confirmed the code has been tested, happy to merge.

**Pull request merged**
