### PR TITLE
feat: add support for fine grained configuration of VPC-flow logs

### PR DESCRIPTION
**Pull request by daniel-cit**
This PR adds support for fine grained configuration of [VPC-flow logs](https://cloud.google.com/vpc/docs/using-flow-logs)

### CODE REVIEW

**Comment by daniel-cit** [comment]
> The files changes look good to me, but looks like there is problem with the build.

@jasonbisson build is green :)

**Review by jasonbisson — APPROVED** [review]
LGTM

**Review by gtsorbo — APPROVED** [review]
LGTM

**Comment by daniel-cit** [comment]
@apeabody @gtsorbo green build 🎉

**Pull request merged**
