### PR TITLE
fix: bump terraform base version from 1.3.0 to 1.3.10

### PR DESCRIPTION
**Pull request by caetano-colin**
Because of the issue described in this link:
https://github.com/hashicorp/terraform/issues/34014

Some users may experience this error:

```text
unsupported checkable object kind "var"
```

This can easily be fixed by upgrading the version to 1.3.10 when using terraform 1.3 series

### CODE REVIEW

**Comment by bdashrad** [comment]
i've been running this project on 1.7.4 without issues, we could probably upgrade even further.

**Review by eeaton — APPROVED** [review]

**Review by fmichaelobrien — APPROVED** [review]
/lgtm
Note: I have been running a full LZ deploy using terraform 1.3.10 override for the last couple deploys - all is good - as expected
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/360

The 0-bootstrap step should be run with 1.3.10 and not 1.5+ or a statefile sync issue will occur in 1-org when we kick in the CB trigger that runs the 1.3.10 container

**Comment by fmichaelobrien** [comment]
reference: https://github.com/terraform-google-modules/terraform-example-foundation/issues/1151

**Pull request merged**
